# Generated by Django 5.1.4 on 2024-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('adhaarcard', models.ImageField(blank=True, null=True, upload_to='adhaarcard/')),
            ],
        ),
    ]
