# Generated by Django 5.1.4 on 2025-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee1_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee1',
            name='company_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='emailid',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='end',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='pancard',
            field=models.ImageField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='pdf1',
            field=models.FileField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='pdf2',
            field=models.FileField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='pdf3',
            field=models.FileField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='pdf4',
            field=models.FileField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='percentage1',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='percentage2',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='percentage3',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='percentage4',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='reason',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='reference',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='reference_no',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='start',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='year1',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='year2',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='year3',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee1',
            name='year4',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='address',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='adhaarcard',
            field=models.ImageField(default='unknown', upload_to='images/Employee2'),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='contact_no',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='father_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='hometown',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
